### PR TITLE
Fix NaN issue in Execa by extracting `.stdout`

### LINKED ISSUE #588: Preflight Docker container with PostgreSQL database: opts.uid is NaN
One of the [latest Preflight test runs](https://github.com/upleveled/pern-extensive-immersive-fall-2024-atvie/issues/114#issuecomment-2418894489) failed with the error `The "options.uid" property must be int32. Received type number (NaN)`:

```
(node:1) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Cloning https://github.com/LrDevEng/next-ecommerce-store...
Installing dependencies...
Setting up PostgreSQL database...
file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/final-error.js:6
	return new ErrorClass(message, options);
	       ^

ExecaError: Command failed with ERR_INVALID_ARG_TYPE: bash ./scripts/alpine-postgresql-setup-and-start.sh
The "options.uid" property must be int32. Received type number (NaN)
    at getFinalError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/result.js:108:16)
    at makeEarlyError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/result.js:45:7)
    at handleEarlyError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/early-error.js:21:21)
    at spawnSubprocessAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:80:10)
    at execaCoreAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:26:32)
    ... 2 lines matching cause stack trace ...
    at file:///preflight/clone-and-preflight.ts:74:5 {
  shortMessage: 'Command failed with ERR_INVALID_ARG_TYPE: bash ./scripts/alpine-postgresql-setup-and-start.sh\n' +
    'The "options.uid" property must be int32. Received type number (NaN)',
  originalMessage: 'The "options.uid" property must be int32. Received type number (NaN)',
  command: 'bash ./scripts/alpine-postgresql-setup-and-start.sh',
  escapedCommand: 'bash ./scripts/alpine-postgresql-setup-and-start.sh',
  cwd: '/preflight/project-to-check',
  durationMs: 3.228265,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  code: 'ERR_INVALID_ARG_TYPE',
  stdio: [ undefined, undefined, undefined ],
  ipcOutput: [],
  pipedFrom: [],
  [cause]: TypeError [ERR_INVALID_ARG_TYPE]: The "options.uid" property must be int32. Received type number (NaN)
      at normalizeSpawnArguments (node:child_process:586:11)
      at spawn (node:child_process:754:13)
      at spawnSubprocessAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:78:16)
      at execaCoreAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:26:32)
      at callBoundExeca (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/create.js:44:5)
      at boundExeca (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/create.js:15:44)
      at file:///preflight/clone-and-preflight.ts:74:5 {
    code: 'ERR_INVALID_ARG_TYPE'
  }
}

Node.js v22.9.0
```

This appears to be coming from this `NaN` value for `uid` being passed here, calculated from `` Number(await execa`id -u postgres`) ``:

https://github.com/upleveled/preflight/blob/d3fbfd0e1ed57c4baaf4e3e4447455933e997edc/docker/clone-and-preflight.ts#L56-L74

We need to investigate why the `postgres` user does not return an `id` - maybe the user doesn't exist?

### PR DESCRIPTION
**Pull request by ProchaLu**
Closes #588

The Preflight Docker container failed when trying to set the `uid` for the PostgreSQL setup script. The issue was that Execa returns an `object`, and `Number()` was called on the object instead of just the command output, resulting in `NaN`. This caused Execa to throw this error:

```bash
'The "options.uid" property must be int32. Received type number (NaN)'
```

It wasn’t clear why the value was `NaN`. We assumed that `execa` returned a `string`, but it returns an `object` containing the command output under `.stdout`. It failed because `Number()` was called on the entire object instead of extracting `.stdout` first. 

```bash
const postgresUid = Number(await execa`id -u postgres`); // Fails: Execa result object → NaN
```

To fix this error, we need to extract `.stdout` before converting to a number.

```bash
const postgresUid = Number((await $`id -u postgres`).stdout); // Works: Extracts string output
```

ESLint didn’t catch this issue because `Number({})` is currently not flagged as an error. A proposal has been made to TypeScript ESLint to introduce a rule preventing passing `objects` to `Number()`.
- https://github.com/typescript-eslint/typescript-eslint/issues/10895

### CODE REVIEW

File: docker/clone-and-preflight.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ if (projectUsesPostgresql) {
   //
   // Example script:
   // https://github.com/upleveled/preflight-test-project-next-js-passing/blob/e65717f6951b5336bb0bd83c15bbc99caa67ebe9/scripts/alpine-postgresql-setup-and-start.sh
-  const postgresUid = Number(await execa`id -u postgres`);
+  const postgresUid = Number((await $`id -u postgres`).stdout);
```
Comment (karlhorky) [inline docker/clone-and-preflight.ts:67]: looks like the `execa` identifier isn't just the one imported directly from the `'execa'` package, but it's this:

```ts
const projectPath = 'project-to-check';
const execa = bindExeca({ cwd: projectPath });
```

so probably we need to stick with using the `execa` identifier, or do a bigger change to switch everything to `$`, with this binding

**Comment by ProchaLu** [comment]
While debugging this issue, we discovered that Execa `$` shorthand behaves differently depending on how it's used. Inside an Execa command, interpolation automatically extracts `.stdout`:

```bash
await $`dep deploy --branch=${branch}`; // Works: `branch` is extracted correctly
```
When assigning the result to a variable, Execa returns an object, not a string, which led to the NaN issue in our case

```bash
const branch = await $`git branch --show-current`;
console.log(branch); // Logs: [object Object]
```

File: docker/clone-and-preflight.ts (hunk 1 above)
Comment (ProchaLu) [reply docker/clone-and-preflight.ts]: Changed to `execa`. [cfc6c4e](https://github.com/upleveled/preflight/pull/629/commits/cfc6c4e6009bb9370c58325ffb656c7839fe911f)

**Review by karlhorky — APPROVED** [review]
LGTM, thanks!
